- hosts: terraform-ansible
  tasks: 
  - name: Instalando o python3, virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: Instalando dependencias com pip (Django e Django Rest)
    pip:
      virtualenv: /home/ubuntu/estudos/venv
      name:
        - django
        - djangorestframework
  - name: Iniciando projeto
    shell: '. /home/ubuntu/estudos/venv/bin/activate; django-admin startproject setup /home/ubuntu/estudos/'
  - name: Alterando host do settings (django)
    lineinfile:
      path: /home/ubuntu/estudos/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes
